# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 18:00
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupScope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=250)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='auth.Group')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='groupscope',
            unique_together=set([('group', 'scope')]),
        ),
    ]
